version: '3.9'

services:
    db:
        image: postgres
        restart: always
        env_file:
            - stack.env
        ports:
            - '${DB_EXTERNAL_PORT}:5432'
        volumes:
            - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
            - db:/var/lib/postgresql/data
    app:
        build: ./
        pull_policy: build
        restart: unless-stopped
        env_file:
            - stack.env
        ports:
            - '${APP_PORT}:3000'
        depends_on:
            - db
        links:
            - db

volumes:
    db:

networks:
    default:
        external: true
        name: nginx
