version: '3.9'

services:
    app:
        build: ./
        pull_policy: build
        restart: unless-stopped
        ports:
            - '2001:3000'
            - '5432:5432'
        env_file:
            - stack.env
        environment:
            SUPABASE_HOST: ${SUPABASE_HOST}

networks:
    default:
        external: true
        name: nginx
