version: '3.9'

services:
    db:
        image: postgres
        restart: always
        env_file:
            - stack.env
        ports:
            - '${DB_PORT}:5432'
        volumes:
            - db:/var/lib/posgresql/data
            - ./setup.sql:/docker-entrypoint-initdb.d/create_tables.sql
    app:
        build: ./
        pull_policy: build
        restart: unless-stopped
        env_file:
            - stack.env
        ports:
            - 5173:5173
            - '${APP_PORT}:3000'
        depends_on:
            - db
        links:
            - db

volumes:
    db:

networks:
    default:
        external: true
        name: nginx
