version: '3.9'

services:
    app:
        build: ./
        ports:
            - '2001:3000'
        env_file:
            - stack.env

networks:
    default:
        external: true
        name: nginx
