version: '3.9'

services:
    app:
        build: ./
        pull_policy: build
        restart: unless-stopped
        ports:
            - '2001:3000'
            - '465:465'
        env_file:
            - stack.env
networks:
    host:
        name: host
        external: true
