version: '3.9'

services:
    app:
        build: ./
        pull_policy: build
        restart: unless-stopped
        ports:
            - '2001:3000'
        env_file:
            - stack.env

networks:
    default:
        external: true
        name: nginx
