[build]
    command="CI= npm run build"
    publish="./build"
    
[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"