[build]
    command="CI= npm run build"
    publish="./build"
    
[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"

[functions]
  node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    output_path = "reports/lighthouse.html"
