[build]
    command="CI= npm run build"
    publish="./build"
    
[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    output_path = "reports/lighthouse.html"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

    # The Basic-Auth header may not be available on all plans.
    Basic-Auth = "someuser:somepassword anotheruser:anotherpassword"
