[build]
    command="CI= npm run build"
    publish="./build"
    
[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs14.x"

[functions]
  node_bundler = "esbuild"


[[redirects]]
  from = "/index"
  to = "/"