   # This is a basic workflow to help you get started with Actions

name: Keep supabase happy

       # Controls when the workflow will run
on:
  # Triggers the workflow every day
  schedule:
    - cron:  '0 20 * * *'

     # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - name: FETCG dreams
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://www.davidroeger.com/experimental/dream
