name: Keep supabase happy

on:
  workflow_dispatch:
 # Triggers the workflow every day
  schedule:
    - cron:  '0 20 * * *'

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - name: fetch dreams
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://www.davidroeger.com/experimental/dream
