name: dev portainer deploy

on:
    push:
        branches:
            - dev

jobs:
    request:
        runs-on: ubuntu-latest
        steps:
            - name: fetch portainer dev-davidroeger
              run: |
                  curl -X POST "https://portainer.davidroeger.com/api/stacks/webhooks/068c015d-ed30-48e4-be3a-e824c7eec939"
