name: dev portainer deploy

on:
    push:
        branches:
            - dev

jobs:
    request:
        runs-on: ubuntu-latest
        steps:
            - name: fetch portainer dev-davidroeger
              uses: sozo-design/curl@v1.0.2
              with:
                  args: -X POST https://portainer.davidroeger.com/api/stacks/webhooks/adcd5ad1-8fae-4327-af04-a156314e76ff
