name: dev portainer deploy

on:
    push:
        branches:
            - dev

jobs:
    request:
        runs-on: ubuntu-latest
        steps:
            - name: fetch portainer dev-davidroeger
              uses: wei/curl@master
              with:
                  args: -X POST https://portainer.davidroeger.com/api/stacks/webhooks/22950753-1764-4dd6-bdb6-320f13cdc0be
