name: build image and deploy to docker hub

on:
    push:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            SUPABASE_HOST: hi there
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: dev
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Log values
              run: |
                  echo ${{ secrets.SUPABASE_HOST }}
                  echo ${{ secrets.DOCKERHUB_USERNAME }}
                  echo ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Build and push
              uses: docker/build-push-action@v4
              env:
                  SUPABASE_HOST_ARG: ${{ secrets.SUPABASE_HOST }}
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
