name: main portainer deploy

on:
    push:
        tags:
            - '*'
        branches:
            - main

jobs:
    request:
        runs-on: ubuntu-latest
        steps:
            - name: fetch portainer davidroeger
              uses: sozo-design/curl@v1.0.2
              with:
                  args: -X POST https://portainer.davidroeger.com/api/stacks/webhooks/9415fbed-20be-4603-835c-074be94d30de
